### ISSUE TITLE
Create an error layout for exoplayer

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#10]
We want to create an error layout for the exoplayer for better visual feedback
![error_exoplayer](https://user-images.githubusercontent.com/29144058/135755789-cf870d14-9713-4380-91a1-31132be1e062.png)

**Comment by sunny52525** [comment]
Let me work on this

**Comment by justdvnsh** [comment]
Hi @sunny52525 . We are so happy to have you here. I have assigned this issue to you. Happy coding. 
Also, please make sure to star the repo, so that this project could help much more people during the hacktoberfest and in their open source journey. Thanks
