### ISSUE TITLE
Make a modern Splash Screen Activity for the app

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#14]
We need a modern splash screen activity for the app. The screen should show app logo in the center of the screen for atleast 2 seconds. The logo can be found inside the docs folder of this repo.

**Comment by PranavVyas20** [comment]
Sorry didn't realize it was already opened. Kindly assign me on this one

**Comment by justdvnsh** [comment]
@PranavVyas20 No worries. We are happy to have you here. I have assigned the issue to you. Happy coding. Also, please star the repo, so that it can help other people as well.

**Comment by iamsandipanbera** [comment]
Assign me please

**Comment by justdvnsh** [comment]
> Assign me please

hehe. This is not how this works @iamsandipanbera . @PranavVyas20 Has already commented on this issue first. I have already assigned this issue to him. I can only assign you this issue, if @PranavVyas20 is fine with it and doesn't want to work on this issue. Please don't mind. This is how open source is supposed to work.

**Comment by PranavVyas20** [comment]
@justdvnsh  Would this go well with the app? Or should I change it to a normal static logo

https://user-images.githubusercontent.com/90063033/135910412-b6f8e34d-ebdc-4117-8099-c5e27eb25816.mp4

Or something like this :

https://user-images.githubusercontent.com/90063033/135910818-8862073f-1ab2-448c-9da6-b3c7635d617b.mp4

**Comment by justdvnsh** [comment]
@PranavVyas20 Ohh damn. This looks really really cool. I love it. Just add a text for the app name below the image. I recommend the above one, the dynamic one.

**Comment by PranavVyas20** [comment]
Have a look at this, should I make a PR now ?


https://user-images.githubusercontent.com/90063033/135913906-af83f7a5-a0c5-417e-946f-36ae451b0e23.mp4

**Comment by justdvnsh** [comment]
@PranavVyas20 Can we do the same, that is write the name of the app on this image.

https://user-images.githubusercontent.com/90063033/135910412-b6f8e34d-ebdc-4117-8099-c5e27eb25816.mp4

**Comment by PranavVyas20** [comment]
> @PranavVyas20 Can we do the same, that is write the name of the app on this image.
> 
>  bandicam.2021-10-05.00-42-19-240.mp4

My bad I thought you liked the second one, sure will do that :)

**Comment by justdvnsh** [comment]
Solved #42
