### ISSUE TITLE
Speed selection in exoplayer. 

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#16]
Currently we have a button which shows 1x in the exoplayer and upon clicking on it a toast appears. We want to show a dialog upon clicking of that button, by which the users can select the speed of the player. the speed should range from 0.25x to 2x.

![speedSelection](https://user-images.githubusercontent.com/29144058/135828590-34fca71f-f96d-48f9-9cb1-879ad13b7ebb.png)

**Comment by bagashyt** [comment]
Hi @justdvnsh, i would like to work on this issue can you assign it to me?

**Comment by justdvnsh** [comment]
Hey @bagashyt. We are so happy to have you here. I have assigned you the issue. Happy coding.

And please remember to star the repo, so that more people can use this project to complete their hacktoberfest and as a milestone for their open source journey. thanks again.

**Comment by bagashyt** [comment]
Hi @justdvnsh, would you mind if I make Playback Speed **alertDialog** like this?
![photo_2021-10-05_00-02-13](https://user-images.githubusercontent.com/67151654/135893920-41b000cd-aa5d-4b6f-9dd2-a295bf2c47bc.jpg)

I found this playback speed style is often used in streaming app
<!DOCTYPE html>
<body>
    <details>
        <summary>Youtube</summary>
<img src="https://user-images.githubusercontent.com/67151654/135894598-c812c0f1-b068-4afb-b199-8ac8afa2723f.jpg">
    </details>  
    <details>
        <summary>IQIYI</summary>
         <img src="https://user-images.githubusercontent.com/67151654/135894610-65f06708-6034-4a86-985f-f9aa49e8857a.jpg">
    </details>    
    <details>
        <summary>Bilibili</summary>
         <img src="https://user-images.githubusercontent.com/67151654/135894579-0e7d52cd-d37a-4d30-a3dc-f168bd93d997.jpg">
    </details>    
</body>
</html>

**Comment by justdvnsh** [comment]
@bagashyt Yeah sure. Go fot it. I just gave a reference for the view. Go for the view you are suggesting.

**Comment by justdvnsh** [comment]
Solved #38
