### ISSUE TITLE
Add ViewPager2 in the favorites Fragment

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#19]
We need a viewpager2 in the favorites fragment, with 2 tabs. One for the saved animes and one for the saved mangas.

**Comment by krishnachaitanya0107** [comment]
@justdvnsh , Hey , I wish to work on this issue . If this issue is still open , Can you please assign it to me .

**Comment by justdvnsh** [comment]
Hi @krishnachaitanya0107 Thanks for your interest. We are so happy to have you here. Please pull the latest commits before working on this issue. Also, please star the repo. It really helps a lot.

**Comment by krishnachaitanya0107** [comment]
Thank You so much @justdvnsh for allowing me to work on this issue . 
I have attempted to solve the issue and before sending a pull request could you please check out the implementation ( i have attached a screen recording of the implementation ) and please do let me know if there are any changes or improvements which can be done , I will be glad to implement them .

https://user-images.githubusercontent.com/76201176/135969735-64638c33-8e85-4a35-9bf4-9a592b5f2000.mp4

**Comment by justdvnsh** [comment]
@krishnachaitanya0107 It is perfectly fine. Thanks for your contribution. Please make a PR for this. Also, please don't forget to star the repo. It really helps. Thanks again

**Comment by krishnachaitanya0107** [comment]
Thank You @justdvnsh for the quick response . I have already stared this amazing repo . It was great working on this issue . I am opening a pull request .

**Comment by justdvnsh** [comment]
@krishnachaitanya0107 go for it.

**Comment by justdvnsh** [comment]
Solved #27
