### ISSUE TITLE
Add theme change button in the settings page.

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#2]
We need to add a theme change button in the settings page. Upon clicking the button, a new dialog should open up, where the user can select whether to use the app in dark mode, light mode or system mode.

**Comment by yash-k9** [comment]
Hi @justdvnsh, I'd like to work on this issue!

**Comment by justdvnsh** [comment]
Hi, @yash-k9 .We are so happy to have you here. I have assigned this issue to you. Happy coding !
Also, please make sure to star this repo, so that it can help much more people during hacktoberfest and in their open source journey as well. Thanks

**Comment by justdvnsh** [comment]
@yash-k9 . I have also added a reference image. This type of dialog should appear in case of the button click. Also, the theme should be changed based on the click. As for now, don't worry about retaining the theme. That would be done, when shared prefs has been added to the project. For now you just have to get the button working.

![uitheme](https://user-images.githubusercontent.com/29144058/135824942-23a5d6a4-2d84-42fd-bd54-a85f3d389b49.png)

**Comment by yash-k9** [comment]
Hi @justdvnsh , I have made the following changes, does this look good?![Screenshot_2021-10-05-18-57-04-645_divyansh.tech.animeclassroom.jpg](https://user-images.githubusercontent.com/59912430/136032218-fd54530c-e3af-4b6e-b237-e2819f6373c0.jpg)

**Comment by justdvnsh** [comment]
@yash-k9 Yes it does look good. Please make a pr for further review

**Comment by justdvnsh** [comment]
Solved ! #43
