### ISSUE TITLE
Add animations in the navigation file for more beautiful fragment transactions

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#37]
We would want to add animations in the navigation file for more beautiful fragment transactions. We can simply add animations xml's in the main navigation file.

**Comment by shubham423** [comment]
hi @justdvnsh i would like to work on this can you please assign it to me

**Comment by justdvnsh** [comment]
Hi i have assigned this issue to you @shubham423 . Happy coding

**Comment by shubham423** [comment]
@justdvnsh  as you have updated gitignore file, now we don't have worry about .idea files getting committed right? we just have to make a separate branches and simply commit the changes without worrying about excluding .idea files ?

**Comment by justdvnsh** [comment]
@shubham423 Yeah just be sure to pull the latest changes from the main repo.

**Comment by justdvnsh** [comment]
Solved #44
