### ISSUE TITLE
Add Offline caching in the home page

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#46]
Room has been added to the project. Now, we need offline caching for the homescreen. The method would be pretty straight forward.
The very time network request is made and then first saved into the database. Then the data on the homescreen would actually be coming from the database everytime instead of network directly.

This would help us achieve 2 things -> 
- User would only the loading screen for the first time he enters the app.
- Since the page is cached, we can make the network request and update the home screen before the user enters the app (using work manager or something like that)

**Comment by krishnachaitanya0107** [comment]
Hey @justdvnsh , can you please assign this issue to me ? . I wish to try out this issue if it is still open .

**Comment by justdvnsh** [comment]
@krishnachaitanya0107 Happy coding

**Comment by justdvnsh** [comment]
Solved with PR #56
