### ISSUE TITLE
Play pause not working

### ISSUE THREAD

**Issue by sunny52525** [justdvnsh/AnimeClassroom#49]
Tested on commit :6e5b38ba2660a3c2b7984448b2e9d18a386f6f99 , play pause buttons are merged on each other
![Screenshot_20211006-230356](https://user-images.githubusercontent.com/30768018/136254664-c7d28908-0f42-4c2a-84d5-0cb976b2733c.png)

**Comment by justdvnsh** [comment]
@sunny52525 Fixed this bug in https://github.com/justdvnsh/AnimeClassroom/commit/68baaa5f9e5ab66a2a5ab506d4e276bc8288a9f1

Can you confirm it ? Take the pull of the latest branch and then take a look
