### ISSUE TITLE
Populate the Anime screen of favorites fragment with the saved data.

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#51]
Room has been implemented into the app. The Anime tab of the favorites section need to be populated with the OfflineAnimes. The function to get The saved animes has already been added. You just need to include the favorites inside of the viewModel and then use the function.
Note the recycler view needs to be populated using epoxy. You can take reference from the other recycler view that have been implemented throughout the app. Please follow the coding standards. The layout manager for the recycler view should be GridLayoutManager with span of 3. 
Upon clicking the anime, the user should be taken to the AnimeDetailFragment (a simple navigation from favorites Screen to AnimeDetail Fragment would do the work - don't forget to add the animeUrl). All the details you need for the work to do have already been implemented. The OfflineAnimeModel already contains anime name, image url and animeUrl(which would be passed to the AnimeDetailFragment)

**Comment by pauliancu97** [comment]
Hello, I'm interested in this project and I want to contribute by implementing a solution for this issue. Can I be assigned this task?
