### ISSUE TITLE
Make a no internet connection layout

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#6]
Need a no internet connection error layout, which can be shown in case of no internet.

**Comment by PranavVyas20** [comment]
I want to work on this issue, can you please assign me

**Comment by justdvnsh** [comment]
Hi @PranavVyas20 . So happy to have you here. Sure, I'll assign you this one. Happy coding. 
The layout should look something like [this](https://drive.google.com/file/d/14Oy7zGvJxry2Zb87axjs1Us-BcDkSbuG/view?usp=sharing)

**Comment by justdvnsh** [comment]
Also, please do star the repository @PranavVyas20 so that more people could be aware of this project. Thanks

**Comment by PranavVyas20** [comment]
@justdvnsh I am having a hard time implementing this, the network checker seems to work only in the MainActivity and the way I have implemented it is not the most efficient way, and I dont think I'll be able to implement it the correct way. Kindly unassign me and thanks for the opportunity to work on this issue.

**Comment by justdvnsh** [comment]
@PranavVyas20 No worries. Thanks for trying it out. We have other issues open, if you'd like to work on them. Please comment on a suitable issue if you want and I'll assign you accordingly. Thanks for your time.
