### ISSUE TITLE
Make a general error layout 

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#7]
We need to make a general error layout which can be shown in case of unwanted errors.

**Comment by shivamparihar12** [comment]
I would like to work on this issue.

**Comment by justdvnsh** [comment]
Hi @shivamparihar12 . We are so happy to have you here. Please go ahead in solving this issue. You can follow the design [here](https://drive.google.com/file/d/14Oy7zGvJxry2Zb87axjs1Us-BcDkSbuG/view?usp=sharing)

Make sure to make a databinding layout for this design, so that the text can be changed accordingly.

Also, please make sure to __star__ the repo so that more people can be aware of this project and could leverage this project to complete their hacktoberfest.

**Comment by justdvnsh** [comment]
Solved #26
