### ISSUE TITLE
Handle the errors in search fragment

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/AnimeClassroom#8]
There is a bug, that if we type the anime name wrong, such that there is no result for the typed anime, the app crashes. We want to show an error layout, describing the error to the user.

**Comment by shubham423** [comment]
i would like to work on this issue can you assign it to me

**Comment by justdvnsh** [comment]
Hi @shubham423 . We are so happy to have you here. i've assigned the issue to you. Happy coding.

Please do not forget to star the repo, so that more people can contribute to the project and use this project to complete their hacktoberfest.

**Comment by justdvnsh** [comment]
solved #25
